In [14]:
import pandas as pd
from utils import cabin_embarked_transformer, title_group_creation, fit_age_imputation, transform_age_imputation, family_size_creation, merge_test

In [15]:
df = pd.read_csv('data/train.csv')
df_merged = merge_test()
df_merged

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0

In [16]:
df = cabin_embarked_transformer(df)
df_merged = cabin_embarked_transformer(df_merged)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,U,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,U,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,U,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,U,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,U,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,U,Q

In [17]:
df = title_group_creation(df)
df_merged = title_group_creation(df_merged)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Title,GroupSize
0,1,0,3,male,22.0,1,0,7.2500,U,S,Mr,1
1,2,1,1,female,38.0,1,0,71.2833,C,C,Mrs,1
2,3,1,3,female,26.0,0,0,7.9250,U,S,Miss,1
3,4,1,1,female,35.0,1,0,53.1000,C,S,Mrs,2
4,5,0,3,male,35.0,0,0,8.0500,U,S,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,U,S,Rev,1
887,888,1,1,female,19.0,0,0,30.0000,B,S,Miss,1
888,889,0,3,female,NaN,1,2,23.4500,U,S,Miss,2
889,890,1,1,male,26.0,0,0,30.0000,C,C,Mr,1
890,891,0,3,male,32.0,0,0,7.7500,U,Q,Mr,1

In [18]:
median_dict = fit_age_imputation(df)
df_cleaned = transform_age_imputation(df, median_dict)
df_merged_cleaned = transform_age_imputation(df_merged, median_dict)
df_merged_cleaned

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Survived,Title,GroupSize
0,892,3,male,34.5,0,0,7.8292,U,Q,0,Mr,1
1,893,3,female,47.0,1,0,7.0000,U,S,1,Mrs,1
2,894,2,male,62.0,0,0,9.6875,U,Q,0,Mr,1
3,895,3,male,27.0,0,0,8.6625,U,S,0,Mr,1
4,896,3,female,22.0,1,1,12.2875,U,S,1,Mrs,1
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,male,29.0,0,0,8.0500,U,S,0,Mr,1
414,1306,1,female,39.0,0,0,108.9000,C,C,1,Dona,1
415,1307,3,male,38.5,0,0,7.2500,U,S,0,Mr,1
416,1308,3,male,29.0,0,0,8.0500,U,S,0,Mr,1
417,1309,3,male,3.5,1,1,22.3583,U,C,0,Master,1

In [19]:
df_cleaned = family_size_creation(df_cleaned)
df_merged_cleaned = family_size_creation(df_merged_cleaned)
df_merged_cleaned

,PassengerId,Pclass,Sex,Age,Fare,Cabin,Embarked,Survived,Title,GroupSize,FamilySize
0,892,3,male,34.5,7.8292,U,Q,0,Mr,1,0
1,893,3,female,47.0,7.0000,U,S,1,Mrs,1,1
2,894,2,male,62.0,9.6875,U,Q,0,Mr,1,0
3,895,3,male,27.0,8.6625,U,S,0,Mr,1,0
4,896,3,female,22.0,12.2875,U,S,1,Mrs,1,2
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,male,29.0,8.0500,U,S,0,Mr,1,0
414,1306,1,female,39.0,108.9000,C,C,1,Dona,1,0
415,1307,3,male,38.5,7.2500,U,S,0,Mr,1,0
416,1308,3,male,29.0,8.0500,U,S,0,Mr,1,0
417,1309,3,male,3.5,22.3583,U,C,0,Master,1,2

In [20]:
df_merged_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Sex          418 non-null    str
 3   Age          418 non-null    float64
 4   Fare         417 non-null    float64
 5   Cabin        418 non-null    str
 6   Embarked     418 non-null    str
 7   Survived     418 non-null    int64
 8   Title        418 non-null    str
 9   GroupSize    418 non-null    int64
 10  FamilySize   418 non-null    int64
dtypes: float64(2), int64(5), str(4)
memory usage: 36.1 KB

In [21]:
df_merged_cleaned.loc[df_merged_cleaned['Fare'].isna()]

,PassengerId,Pclass,Sex,Age,Fare,Cabin,Embarked,Survived,Title,GroupSize,FamilySize
152,1044,3,male,60.5,NaN,U,S,0,Mr,1,0

In [22]:
fare_median = df_cleaned['Fare'].median()
df_merged_cleaned['Fare'] = df_merged_cleaned['Fare'].fillna(fare_median)
df_merged_cleaned

,PassengerId,Pclass,Sex,Age,Fare,Cabin,Embarked,Survived,Title,GroupSize,FamilySize
0,892,3,male,34.5,7.8292,U,Q,0,Mr,1,0
1,893,3,female,47.0,7.0000,U,S,1,Mrs,1,1
2,894,2,male,62.0,9.6875,U,Q,0,Mr,1,0
3,895,3,male,27.0,8.6625,U,S,0,Mr,1,0
4,896,3,female,22.0,12.2875,U,S,1,Mrs,1,2
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,male,29.0,8.0500,U,S,0,Mr,1,0
414,1306,1,female,39.0,108.9000,C,C,1,Dona,1,0
415,1307,3,male,38.5,7.2500,U,S,0,Mr,1,0
416,1308,3,male,29.0,8.0500,U,S,0,Mr,1,0
417,1309,3,male,3.5,22.3583,U,C,0,Master,1,2

In [25]:
df_merged_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Sex          418 non-null    str
 3   Age          418 non-null    float64
 4   Fare         418 non-null    float64
 5   Cabin        418 non-null    str
 6   Embarked     418 non-null    str
 7   Survived     418 non-null    int64
 8   Title        418 non-null    str
 9   GroupSize    418 non-null    int64
 10  FamilySize   418 non-null    int64
dtypes: float64(2), int64(5), str(4)
memory usage: 36.1 KB

In [24]:
df_cleaned.to_csv('data/cleaned_train.csv', index=False)
df_merged_cleaned.to_csv('data/cleaned_test.csv', index=False)